### ISSUE TITLE
No such module 'LDSwiftEventSource'

### ISSUE THREAD

**Issue by lrodriguezcds** [DevCycleHQ/ios-client-sdk#113] opened 2023-01-01 02:27 UTC
Hi everyone! I am getting a `No such module 'LDSwiftEventSource'` when updating to version 1.5.0. I am using Xcode's Package dependencies, any chance this is an issue on the SDK side when using the Xcode's Package dependencies? Thanks!

**Comment by kaushalkapasi** [comment] 2023-01-03 16:09
Hi @lrodriguezcds,

Were you able to resolve this issue by updating to the latest version of the SDK `1.6.0`? If not, we can investigate this further!

**Comment by lrodriguezcds** [comment] 2023-01-03 17:51
Hi @kaushalkapasi! No, I was not able to solve the issue yet. 

Answering your question, I am seeing the error in the version `1.6.0` as well. It seems it can't find the module .. I tried to add the dependency with the issue (`LDSwiftEventSource`) manually (via Xcode's Package Dependencies)  but when I do that I get the error mentioned here  https://github.com/DevCycleHQ/ios-client-sdk/issues/114

<img width="1165" alt="Screen Shot 2023-01-03 at 14 39 13" src="https://user-images.githubusercontent.com/46491828/210412495-15b82b54-cfac-47f7-8364-b66a6dc3b6ec.png">

Tried to run it on a real device and without having selected any simulator just in case but get the same error.  

Thank you so much for your time!

**Comment by kaushalkapasi** [comment] 2023-01-03 19:12
Hi @lrodriguezcds, we've published a new version `v1.6.1` with a fix for this issue.

Let us know once you have verified it and we can close this issue!

**Comment by lrodriguezcds** [comment] 2023-01-03 19:40
I've updated to vertion 1.6.1 and once cleaned and built I am seeing this error in Xcode 

<img width="348" alt="Screen Shot 2023-01-03 at 16 35 10" src="https://user-images.githubusercontent.com/46491828/210429203-5342ce4d-1db0-4244-94cb-67ccbea5d877.png">

**Comment by kaushalkapasi** [comment] 2023-01-03 19:56
@lrodriguezcds taking a look! will update you shortly!

**Comment by kaushalkapasi** [comment] 2023-01-03 20:51
@lrodriguezcds published `v1.6.3` with the fix! thanks for your patience on this!

**Comment by lrodriguezcds** [comment] 2023-01-03 21:22
No problem @kaushalkapasi! Thank you for taking the time to review and fix this! 

Now it is compiling when upgrading to version `1.6.3` but I tried the feature flags and it seems  the `onUpdate` callback is not being fired (not even at initialization time..) We are aiming to update to a higher version to be able to make use of the real time update! 🙌  but now it seems it is not going through the `onUpdate` not even when we first run the app (that is working in the previous version (1.3.1) )

<img width="617" alt="Screen Shot 2023-01-03 at 18 14 26" src="https://user-images.githubusercontent.com/46491828/210442908-6086fdeb-cd5d-452d-92bc-0d69da477ff8.png">

Thank you!

**Comment by kaushalkapasi** [comment] 2023-01-03 21:49
@lrodriguezcds the `onUpdate` handler will get triggered every time the value changes when compared to the previous value for a specific User based on the variation they are receiving. You'll also need to hit save on the Feature page after updating the Variable / Variation values in order to trigger a realtime update!

Hopefully our [iOS Realtime Updates Docs](https://docs.devcycle.com/docs/sdk/client-side-sdks/ios#variable-updates) can clarify things!

**Comment by lrodriguezcds** [comment] 2023-01-04 11:05
Hi @kaushalkapasi! Thank you for the link! I am doing exactly what you mentioned i.e changing the value on the console and hitting "save" however the realtime update is not being triggered and neither when the app first loads, what I mean by this is that it is not bringing the flag value from DevCycle when I first run the app.

As I mentioned, the same code is working fine in version `1.3.1 `but with the version (`1.6.3`) the `onUpdate` is not being triggered. I am looking at the docs and it seems we are doing what the doc says we have to do, so this seems to be a problem with this version since version `1.3.1` works ok!

Just in case, we are sending the user as anonymous (`.isAnonymous(true)`) however if we remove the anonymous property and send a userId instead, the problem remains (the flag is not updated on the app because the `onUpdate` is not being triggered).

Thanks you!

**Comment by kaushalkapasi** [comment] 2023-01-04 14:24
Hi @lrodriguezcds,

Thanks for confirming! Is there a way you could share a minimum reproduction of your app? Additionally, join us on the [DevCycle Discord](https://discord.gg/44dgPR8e) and we can get some more eyes on this issue!

Note: the DevCycle Discord link is limited to 5 uses & expires in 24 hours!

**Comment by lrodriguezcds** [comment] 2023-01-04 15:33
Hi @kaushalkapasi, yes sure. 

In the `didFinishLaunchingWithOptions` method we configure DevCycle as it follows:

```
let user = try? DVCUser.builder()
            .isAnonymous(true)
            .build()
        
        if let user = user {
            dvcClient = try? DVCClient.builder()
                .environmentKey(Config.shared.devCyclenvironmentKey)
                .user(user)
                .build(onInitialized: nil)
        }

_ = dvcClient?.variable(
            key: key,
            defaultValue: defaultValue
        ).onUpdate(handler: { newValue in
            self.isFlagEnabled = newValue
        })
```

The line `self.isFlagEnabled = newValue` is not being executed.

**Comment by kaushalkapasi** [comment] 2023-01-05 18:56
Hey @lrodriguezcds, found a few things that I wanted to share with you that should fix your problem! Let me know if this works for you!

1. When using a DevCycle Variable (as you have here), its using a weak-reference which means the `onUpdate` reference is lost once that code is executed. The way to solve this, will be to create a variable in scope of the class where you want to use the variable so that a strong reference exist throughout the lifecycle of your app and updates can be triggered!

2. For the issue where the `onUpdate` is not being triggered initially, this is due to the caching that has been introduced in newer versions of the SDK. I've added a line for how the Variable can be read initially, before an `onUpdate` is triggered in the example below.

```
var myBooleanDevCycleVariable: DVCVariable<Bool>?         // fix for point 1

self.myBooleanDevCycleVariable = dvcClient?.variable(     // fix for point 1
    key: key,
    defaultValue: defaultValue
).onUpdate(handler: { newValue in
    self.isFlagEnabled = newValue
})

self.isFlagEnabled = self.myBooleanDevCycleVariable.value // fix for point 2
```

**Comment by lrodriguezcds** [comment] 2023-01-05 19:48
Will try it and let you know!

**Comment by lrodriguezcds** [comment] 2023-01-06 09:50
Hi @kaushalkapasi!

Awesome! I have updated the code with the suggested changes and the realtime updates and initialization are working now! 

Thank you your help!! 🙏

**Closed** 2023-01-06 15:55 UTC
